### ISSUE TITLE
Plugin removal from wordpress svn not getting affected in pluginmirror

### ISSUE THREAD

**Issue by s3bubble** [bluehost/pluginmirror#12]
Hi All,

We contacted WordPress who removed our plugin from the svn months ago but after searching it is still showing on this repo please remove.

Its no longer listed
https://wordpress.org/plugins/search/s3bubble-amazon-s3-html-5-video-with-adverts/

But you still have it listed here.
https://github.com/wp-plugins/s3bubble-amazon-s3-html-5-video-with-adverts/

Please remove this plugin.

Thanks

**Comment by tierra** [comment]
WordPress only de-lists plugins, they don't ever remove them entirely, and this is a mirror of the SVN repository, which never removes plugins after they are added:
http://plugins.svn.wordpress.org/s3bubble-amazon-s3-html-5-video-with-adverts/trunk/

**Comment by s3bubble** [comment]
Hi @tierra,

Thanks for making that clear I have removed everything.

http://plugins.svn.wordpress.org/s3bubble-amazon-s3-html-5-video-with-adverts/trunk/

Sam
