### ISSUE TITLE
Updates don't appear to be working

### ISSUE THREAD

**Issue by thebrandonallen** [bluehost/pluginmirror#5]
The number of plugins in the "Updating" category on the status page seems to have been consistently rising for at least a week. One plugin I follow was updated on the 9th in the .org repo, but the changes haven't been mirrored to GitHub. I've been watching the status page since then, and haven't seen any downward movement. For example, most of the WP community (developers at least) is aware of the recent security fixes for WordPress SEO by Yoast, but it's changes haven't been mirrored, despite being released 5 days ago.

**Comment by MikeHansenMe** [comment]
Thanks for letting us know. We are aware of the updating problem and it is being worked on currently. I will post here once there is an update.

**Comment by thebrandonallen** [comment]
No worries. I hadn't seen any mention of it, so just wanted to make sure someone was aware. It probably doesn't get said enough, but thanks for all the work you and the team put into this. It's a huge asset.

**Comment by thebrandonallen** [comment]
Everything appears to be back in order. Thanks again!
