### ISSUE TITLE
Added My Own Plugins

### ISSUE THREAD

**Issue by technofreaky** [bluehost/pluginmirror#6]
I am having about 10 plugin's hosted in wp plugins directory

all my plugins are hosted in wp & github. i want to use github for tracking issues and releases. 

and one of my plugin's issue was automatically referred from wp to github.

how this can be done. ?  

https://github.com/technofreaky/WooCommerce-Attributes-Menu-Manager/issues/1

https://github.com/technofreaky/WooCommerce-Attributes-Menu-Manager

**Comment by MikeHansenMe** [comment]
You just need to find your plugin on pluginmirror.com and click clone. This will add it to the queue. Once it gets cloned it will be available on github.

**Comment by technofreaky** [comment]
Hi
i have already hosted on github. i just want to link my repo on pluginmirror.com

**Comment by MikeHansenMe** [comment]
Hi Varun, the pluginmirror only mirrors plugins that are hosted on
wordpress.org. If your plugins are there they will get mirrored here on the
pluginmirror github repo.
